version: "3"

services:
  mysql:
    image: mysql:8

    ports:
      - 3306:3306
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - django-network

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    container_name: django
    depends_on:
      - mysql
    networks:
      - django-network

networks:
  django-network:
    driver: bridge

volumes:
  db:
